### ISSUE TITLE
Average subject

### ISSUE THREAD

**Issue by rafaloz** [Deep-MI/FastSurfer#118]
## Feature Description
Is there an option in FastSurfer to create averaged runs for the same subject with different T1 acquisitions as FreeSurfer's make_average_subject?

Thanks for your help,

Rafa

**Comment by m-reuter** [comment]
Hi Rafa, 

the `make_average_subject` command is run after `recon-all` in FreeSurfer and similar to other post processing (subfields etc) can be performed after FastSurfer and `recon-surf` are done. From the description https://surfer.nmr.mgh.harvard.edu/fswiki/make_average_subject I cannot see exactly what files are needed as input but I think at least: orig, white, pial, inflated for each hemi and volumes for orig, brain, and T1. Those files should all be available after a default FastSurfer run, and therefore calling `make_average_subject`  after FastSurfer should work out of the box. 

General note on post processing scripts:
Some post processing may require specific files to be available and some of those are currently not created in the default pipeline under the regular FreeSurfer name, but have a different name (usually with "mapped" in the file name). In order to run those pipelines, e.g subsegmentations, just create a symbolic link from mapped file to the expected input file. If unclear which file should be used, ask here.

**Comment by rafaloz** [comment]
It ask for (lh/rh).sphere.reg, is there a similar file for FastSurfer?

**Comment by m-reuter** [comment]
You need to run fastsurfer with the -- surfreg flag so that it generates the spherical registrations

**Comment by rafaloz** [comment]
ok, thank you very much!
