### ISSUE TITLE
Support FastSurfer on Windows

### ISSUE THREAD

**Issue by Siebenstein83** [Deep-MI/FastSurfer#174]
Hi,

I am trying to run FastSurfer with Docker under Windows (10 Enterprise 19042.1826 on an Intel computer with NVidea Quadro K4200). 

So today I installed Docker for Windows (v4.10.1) an then both downloaded the fastsurfer image from Dockerhub and built an image per your instructions with the "docker build" command.
But I can not get either to run using the "docker run" command with the parameters given in your Docker readme (https://github.com/Deep-MI/FastSurfer/tree/stable/Docker).
If I enter the command as is written the readme, I get the message that docker run requires at least 1 argument (namely the image). When I start with "docker run fastsurfer:gpu", I am told that the following parameters are not recognized. What am I doing wrong?

![image](https://user-images.githubusercontent.com/39907098/181258536-94b26947-970d-4008-9753-e94a6e3fde17.png)

**Comment by LeHenschel** [comment]
Hey,

overall, the first command is the one that should work
`docker run --gpus all -v //d/MRI_data:/data --rm --user root fastsurfer:gpu --t1 /data/S0180/orig.mgz --sid S0180 --sd /data --fs_license /data/freesurfer_license.txt --parallel`

You have to first define the [mappings to the windows directory](https://medium.com/@kale.miller96/how-to-mount-your-current-working-directory-to-your-docker-container-in-windows-74e47fa104d7) via the -v flag, then define the docker image (fastsurfer:gpu) and then the specific flags for the run. To test what is going on, you might also omit the run specific flags and see if the help message is correctly displayed (... fastsurfer:gpu --help). 

Also, can you specify the exact command you used to build the docker image? What if you pull the image from the repository (docker pull deepmi/fastsurfer:gpu-v1.1.0) and run the command:
`docker run --gpus all -v //d/MRI_data:/data --rm --user root deepmi/fastsurfer:gpu-v1.1.0 --t1 /data/S0180/orig.mgz --sid S0180 --sd /data --fs_license /data/freesurfer_license.txt --parallel`

Finally, last time I checked, Windows did not support GPU in docker, which might be a problem (try removing the "--gpus all"). 

EDIT: Seems like Window supports GPU pass through to WSL2 now. Not sure if you set up your system accordingly?
https://ubuntu.com/blog/getting-started-with-cuda-on-ubuntu-on-wsl-2
https://stackoverflow.com/questions/49589229/is-gpu-pass-through-possible-with-docker-for-windows

**Comment by Siebenstein83** [comment]
Hi, 

thanks for the fast reply! 

I built the docker image exactly as specified in your Docker-Readme. 

With both the pulled image, and the built image, I
- get the "docker run requires at least 1 argument" error when the "fastsurfer:gpu" or "deepmi/fastsurfer:gpu" argument doesn't follow immediately after "run"
- get the error that the "--gpus" flag is not recognized 
- get the error that the "-v" flag is not recognized
- find that in the help (called with "--help") neither the "gpus" nor "v" flags are mentioned

I have no idea yet if my system is set up for using GPUs in Docker (if the "--gpus" flag doesn't work, maybe not). I can look at the links that you provided tomorrow. Without GPUs, I suppose the running time would be considerably longer?

Also, could I try to run using only explicit paths instead of mappings with "v" flags?

Do you know if GPUs are supported in Singularity under Windows? If we don't get the Docker running soon, I'd be tempted to try that approach instead. At the moment, all the computers and servers in our lab that have GPUs are running Windows only. So in order to do a native install (which probably would be the approach most likely to work?), we'd first have to install Linux with corresponding GPU drivers.

**Comment by LeHenschel** [comment]
Ok, I think there is some confusion how docker works here. I will try to explain a bit. The general command consists of Two large parts (DOCKER and FASTSURFER). Each of these parts has sub options (FLAGS):

DOCKER DOCKER-FLAGS FASTSURFER FASTSURFER-FLAGS

which translates to e.g.
docker run -v //c/volume_on_computer:/name_in_container --gpus all fastsurfer:gpu --help

DOCKER = docker run
DOCKER-FLAG = -v //c/volume_on_computer:/name_in_container --gpus all (or anything listed in docker run --help)
FASTSURFER = fastsurfer:gpu (= called an image in docker lingo)
FASTSURFER-FLAG = --help or --t1, --sd, --sid ... (everything listed in docker run fastsurfer:gpu --help)

> find that in the help (called with "--help") neither the "gpus" nor "v" flags are mentioned

The -v and --gpus flag are DOCKER-FLAGS. They always come before the docker image (=FASTSURFER) and are not directly related to Fastsurfer. Therefore they are not mentioned in the help text. which only covers FastSurfer specific stuff (e.g. things you need to specify if you run no matter if you use docker or a local install)

> get the "docker run requires at least 1 argument" error when the "fastsurfer:gpu" or "deepmi/fastsurfer:gpu" argument doesn't follow immediately after "run"

The fact that you get no error message, when removing the --gpus and -v flag suggests that the problem is on the DOCKER side, not the FASTSURFER side. Does it work if you only remove the --gpus flag? In this case I would assume, that you are NOT set-up to run docker with gpus at all, but the mappings are correctly recognized.

> Also, could I try to run using only explicit paths instead of mappings with "v" flags?

No, without the mappings, the directories are not visible inside the container (docker has no way to access your local file system otherwise).

> Do you know if GPUs are supported in Singularity under Windows?

I think you would also need WLS2 installed just as for docker (https://github.com/apptainer/singularity/issues/4518#issuecomment-678545845, https://sylabs.io/2022/03/wsl2-gpu/). With a new Windows system (most recent 10 or 11) wsl installation is basically just one command `wsl --install`. The links in my last post and this one have a detailed step-by-step instruction.

> Without GPUs, I suppose the running time would be considerably longer?

Yes, GPU is recommended becaue CPU is a lot slower. The running times on CPU are improved in the newest FastSurfer version (dev, https://github.com/Deep-MI/FastSurfer/pull/171)

**Comment by Siebenstein83** [comment]
> Ok, I think there is some confusion how docker works here

Yup, which flags were for docker and which for FastSurfer wasn't immediately clear to me. Thanks for clearing this up.

I now got FastSurfer to start running without GPU support. This indeed seems to be an issue with my system and/or Docker installation, I've now tried to figure out if it can be enabled. The instructions in the above link seem to be outdated however, so I guess I'd have to do some more digging to get there. We are also now planning to talk to our IT department if it's possible to install Fastsurfer on a Linux server, this might be the less troublesome way to go in the end.

**Comment by m-reuter** [comment]
Probably the easiest way is to install docker on linux and run FastSurfer in Docker.

**Comment by dkuegler** [comment]
the nvidia-docker container runtime is not compatible with a windows host system
https://github.com/NVIDIA/nvidia-docker/wiki#is-microsoft-windows-supported

You have to use FastSurfer natively (on Windows) or use FastSurfer in CPU mode within a docker container on Windows.

**Comment by m-reuter** [comment]
This should stay open until we investigate what works and what not on windows. FastSurferCNN may work natively, but not recon_surf (due to FreeSurfer). Also, as @LeHenschel has pointed out above, Nvidia-docker is not the only way to pass-through a GPU. https://stackoverflow.com/questions/49589229/is-gpu-pass-through-possible-with-docker-for-windows and WSL2 has worked for others. So it should be possible to run a docker with GPU on Windows 11 (maybe 10). Could be that it needs to be a second GPU, not the one used for driving the monitor, however.

**Comment by m-reuter** [comment]
Documentations have been updated in #244 
FastSurfer runs in Docker on Windows both for CPU and Nvidia GPU.
