### ISSUE TITLE
Integrate CerebNet into FastSurfer

### ISSUE THREAD

**Issue by dkuegler** [Deep-MI/FastSurfer#204]
## Feature Description
Integrate the CerebNet code, models and scripts into the FastSurfer pipeline
1. Identify redundant code
2. Integrate new code
3. Update call interface (commandline support to call cerebnet through the main entrypoint script (run_fastsurfer.sh)
4. Add validation testing to confirm results are consistent with the original publication

## Motivation
CerebNet provides subsegmentation of the cerebellum which is complementary to FastSurfer. We chose FastSurfer as the main reproducibility, code and support platform.

## Additional Context
Faber J*, Kügler D*, Bahrami E*, Heinz LS, Timmann D, Ernst TM, Deike-Hofmann K, Klockgether T, van de Warrenburg B, van Gaalen J, Reetz K, Romanzetti S, Oz G, Joers JM, Diedrichsen J, ESMMR Study Group, Reuter M. (*co-first). CerebNet: A fast and reliable deep-learning pipeline for detailed cerebellum sub-segmentation. NeuroImage. 2022.
DOI: [ 10.1016/j.neuroimage.2022.119703](http://dx.doi.org/10.1016/j.neuroimage.2022.119703)

**Comment by dkuegler** [comment]
Update:
1-3 are done.
4 is in progress

**Comment by dkuegler** [comment]
#208 establishes an interface that makes CerebNet integrate-able and code de-duplication between "modules".

**Comment by LeHenschel** [comment]
We should add the PYTHONPATH in the Dockerfile because currently the build fails (download_checkpoints.py does not find FastSurferCNN module).

**Comment by LeHenschel** [comment]
Also with the torch version in requirements, mps does not exist as a callable module yet (AttributeError: module 'torch.backends' has no attribute 'mps')

**Comment by af-a** [comment]
@LeHenschel

From some quick tests, all other Dockerfiles build successfully after setting `PYTHONPATH`; the only issues are in the FastSurferCNN images already mentioned.

> With the new module structures, the checkpoint download fails (independent of the PYTHONPATH). Reason is, that we only copy FastSurferCNN folder, not the entire thing. I changed the Dockerfile_FastSurferCNN in my aseg_brainmask_module branch

Note that only setting `PYTHONPATH` in these images is not sufficient because python only recognizes modules that are one directory lower than the added directory in the hierarchy (e.g. adding `/fastsurfer/FastSurferCNN` or `[ANYTHING]/FastSurferCNN` works; adding `/FastSurferCNN` itself doesn't).
If you don't want to include an extra `/fastsurfer` directory to fix this, we could instead add the root directory to the `PYTHONPATH` in these images (i.e. `ENV PYTHONPATH=/:$PYTHONPATH`). Not sure if this is a better solution though.

**Comment by LeHenschel** [comment]
Yes, in the Dockerfile_FastSurferCNN I copied FastSurferCNN into /fastsurfer/FastSurferCNN and set the PYTHONPATH to /fastsurfer. I think we should do this for all docker files (see #212)

**Comment by dkuegler** [comment]
@AhmedFaisal95 @LeHenschel this is the CerebNet PR, the points/discussion here are part of PR #208 . ;-)

**Comment by kkaiwang07** [comment]
@dkuegler 
Hello, now I want to use cerenet to segment the cerebellum, but I can't find the cerebet code on github. How can I use the cerenet code?

**Comment by dkuegler** [comment]
Solved by #258
