### ISSUE TITLE
--surfreg in FastSurfer VINN 2.0.0

### ISSUE THREAD

**Issue by rcruces** [Deep-MI/FastSurfer#240]
## Question/Support Request

Hi I just ran the new version of the pipeline and the results and the processing times are outstanding. However I noticed two minor issues.
1) can we do manual edits to the mask and then run your spectral spherical projection, just for minor edits. Only in those areas where the meninges are really close to the grey matter. 
2) The sphere.reg file was not generated even when I did not used the --no_surfreg flag. is this a normal behaviour? can I generate this file for further registrations? in the readme it says that: "For surface group analysis, sphere.reg is also generated automatically by default. "

## Screenshots
![surf_detail](https://user-images.githubusercontent.com/15281416/212218774-7e7d1963-44e2-4dc6-8d1d-719ceccf591d.png)

...

## Environment
 - FastSurfer Version: Docker Build CPU FastSurfer Image v2.0.0
 - FreeSurfer Version: Docker Build CPU FastSurfer Image v2.0.0
 - OS: Ubuntu mate 1.20.1
 - CPU: 15
 - 

### Execution

**build**
```
cd ..
docker build --rm=true -t my_fastsurfer:cpu -f ./Docker/Dockerfile_CPU .
```

**run**
```
docker run -v ${T1w}:/data/${idBIDS}_t1w.nii.gz \
        -v "${SUBJECTS_DIR}":/output \
        -v "${fs_licence}":/fs_license/license.txt \
        --user "$(id -u)" --rm my_fastsurfer:cpu \
        --t1 /data/${idBIDS}_t1w.nii.gz \
        --sid ${idBIDS} --sd /output \
        --fs_license /fs_license/license.txt \
        --parallel --threads ${threads} --device cpu \
        --no_fs_T1 --vox_size min
```

**Comment by m-reuter** [comment]
Thanks for trying the new version. These are actually 2 separate issues. If the solution to 1. below works, we can keep it like this, if not, please open a separate issue for the editing where we can discuss this further. 

1. in version 2.0 you should be able to do this by running the segmentation and recon-surf steps separately. The segmentation will create  its output under /home/user/my_fastsurfeer_analysis/subjectX/mri/aparc.DKTatlas+aseg.deep.mgz, mask.mgz, and orig.mgz . You can then edit mask.mgz and run the surface stage without specifying inputs. It should not re-create those files but use them for the surface creation. 

2. missing sphere.reg could be a bug and needs replication. Due to the OHBM deadline tonight, this will probably be looked at next week.

**Comment by LeHenschel** [comment]
Hey,

I ran the command with the docker from our docker hub (deepmi/fastsurfer:cpu-v2.0.0) and it automatically produced the ?h.sphere.reg:
```
docker run -v $PWD:/data -v /fs732:/fs732 \
                 --user "$(id -u)" --rm deepmi/fastsurfer:cpu-v2.0.0 \
                 --t1 /data/IXI/IXI002-0828-T1.nii.gz \
                 --sid IXI002-0828 --sd /data/surfreg \
                 --fs_license /fs732/.license \
                 --parallel --device cpu \
                 --no_fs_T1 --vox_size min
```
Also build the docker from scratch and it generated the sphere.reg files as it should. Are you sure you updated your github branch accordingly? I would also be helpful if you can share your log-file (recon-surf.log) for further debugging.

**Comment by rcruces** [comment]
Hi, I build the container from the stable branch and `git pull` it right before building it. And I followed the example from the README file inside  `/docker`. 
However,  I notice a difference now, your docker container was downloaded from the Docker hub `deepmi/fastsurfer:cpu-v2.0.0` and mine build from my local github which created this image `my_fastsurfer:cpu`.
 Do you think this may lead to the different results? I am now downloading this `deepmi/fastsurfer:cpu-v2.0.0` and I'll re-run the tests.

**Comment by LeHenschel** [comment]
The name should not matter. Basically the name that you put after the -t flag in the docker build command sets the name for the image. The content is identical (if the same Dockerfile is used, which should be the case here).

But it is strange, that stable does not include the correct changes for you. Maybe you can `git pull origin stable` again to make sure all changes are included? Or you can check if line 28 in recon-surf is equal to v2.0.0 (`fssurfreg=1           # run FS surface registration to fsaverage, if 0 omit this step`; https://github.com/Deep-MI/FastSurfer/blob/stable/recon_surf/recon-surf.sh#L28)

Rerunning the surfreg only is also possible. See #227

**Comment by m-reuter** [comment]
Any progress on this? @rcruces did it work with our distributed docker images? Also if you build your own images, make sure you checkout our stable branch into a fresh directory. That way you avoid any git related things (like checking from your own fork, rather than from ours, or merging accidentally with a local branch with other changes etc).

**Comment by rcruces** [comment]
Hello, thank you for the follow up. I re-build my own image, and I download the distributed docker image. Tested both and now everything is there. We are now testing the corrections to the `mask.mgz`.

**Comment by m-reuter** [comment]
For the mask edit, we also put some info on how to run the two stages separately here:
 https://github.com/Deep-MI/FastSurfer/blob/dev/recon_surf/README.md#manual-edits
Other edits are currently not easily possible. 

Closing this issue for now. Requests for manual editing options should be started as a new issue. 

And the missing surfreg could be resolved by using our released containers and by building fresh ones from stable.
