### ISSUE TITLE
Manual Editing Brain Mask

### ISSUE THREAD

**Issue by psimonjones** [Deep-MI/FastSurfer#290]
Is there a way to add your own brainmask and use the -noskullstrip option as can be done in FreeSurfer recon? FastSurfer if chopping off the temporal lobes of atrophied brains in a similar way that Freesurfer does, but I cannot see how you fix these issues.

**Comment by m-reuter** [comment]
Hi, the brainmask gets created from the segmentation (some spatially varying iterations of dilation and erosion of the union of all labels). That means you can edit the brainmask and then run the recon-surf part which will automatically use the modified brainmask. It probably make sense to also edit the segmentation directly and create the correct gray matter and white matter labels in that region. The recon-surf part should then work as expected. 

Do you have example cases (e.g. IDs from publicly available datasets where you see this problem)? We probably can look for it in the training data and eventually fix it, so that FastSurfer does not replicate those issues in a future version.

**Comment by psimonjones** [comment]
Using Freesurfer pipeline we might typically have to edit/provide brainmask.mgz, colour in bits of aseg.presurf.mgz and also add white matter control points. Following your comments and looking at the time stamps of the output of run_fastsurfer.sh I see the brainmask.mgz is downstream of some other files like aparc.DKTatlas+aseg.deep.mgz, mask.mgz, aparc.DKTatlas+aseg.orig.mgz. Do you mean edit the file aparc.DKTatlas+aseg.deep.mgz? I may be able to deface an example to send to you.

**Comment by m-reuter** [comment]
Yes the pipeline in FastSurfer works different from FreeSurfer. The order of things is slightly different. 
Our segmentation module is at the beginning and creates the aparc.DKTatlas+aseg.deep.mgz based on which it then creates the brainmask and also reduces the labels to an aseg.mgz. After manual edits to the aparc.DKT... this can be repeated via the command:
`python3 reduce_to_aseg.py -i aparc.DKTatlas+aseg.deep.edited.mgz -o subject/mri/aseg.auto_noCCseg.mgz -outmask subject/mri/mask.mgz --fixwm`
After that you can start the surface module (recon-surf). Sometimes it may be sufficient to only edit the brainmask and restart the surface pipeline but if GM and WM regions are missing, you probably need to add them back in in the segmentation file first. 

That describes aparc and brainmask edits. Further edits that possibly affect the stream are intensity changes to the input image. For example, users sometimes run a bias field correction on the image before they send it to FastSurfer. This can help brighten the regions in the temporal lobe which in turn will affect its segmentation. It is worth a try. 

WM control points cannot be set. Also manual edits to brainfinal.surf (for edits around the cerebellum) cannot be performed as there is no way to enter the pipeline at that stage again. But we plan to add that at a later stage.

Currently possible edits are:
- prior image improvements (e.g. bias field removal)
- aparc.DKTatlas+aseg.deep.mgz directly affecting brainmask, aseg and therefore surfaces (basically everything)
- additional brainmask edits, e.g. if it needs to be tighter in places, because surfaces grab dura etc

The first you would do before you start FastSurfer, the second and third would be done after the segmentation module and before starting the surface module. 

We need to document this better somewhere. But editing has not yet been a priority.

**Comment by psimonjones** [comment]
Thanks you for the detailed response and sorry for not replying earlier. Atrophy from FTD can create enlarged ventricles and in semantic variant primary progressive aphasia this can be prominent in the inferior lateral ventricles, usually predominantly left but also right sided is possible. Below is a typical failure though in some cases more tissue is misidentified.

![sd](https://github.com/Deep-MI/FastSurfer/assets/24224011/8eb1b8c6-f2de-42f0-a894-2e645ab0ee43)

![sd2](https://github.com/Deep-MI/FastSurfer/assets/24224011/28b0a3e5-b2a4-437f-b2b7-90e900e25ac3)

The emphasis on the DKT atlas may not be helpful for this disease group. DKT removed the temporal pole from the DK atlas as it was not well-defined. But the temporal pole is an important region in this disease as atrophy here relates to the clinical symptoms.

There is the Neuroimaging in Frontotemporal Dementia dataset here https://ida.loni.usc.edu/login.jsp which requires an application. We would be happy to make available examples to you, but they would be defaced unfortunately.

**Comment by m-reuter** [comment]
we added a description, more edits will follow in the future, closing this for now.
