### ISSUE TITLE
Problems generating HDF5 file with simple data

### ISSUE THREAD

**Issue by jhlegarreta** [Deep-MI/FastSurfer#303]
## Question/Support Request

Hello,
I am trying to build an own HDF5 dataset using the `generate_hdf5.py` script, with the data that can be found in the following link (a single subject, nothing fancy, just for experimental purposes) and the options below.

The script fails first at
https://github.com/Deep-MI/FastSurfer/blob/d0fdf8346c840283bdbb4cc2f97c228204fa605a/FastSurferCNN/data_loader/data_utils.py#L533

with the error message
```
Volume: 0 Failed Reading Data. Error: Error: CC classes (251-255) still exist in aseg
```

If I change the mentioned line to
```
assert not np.any((aseg >= 251) & (aseg <= 255))
```

then the check passes, but the process fails at
https://github.com/Deep-MI/FastSurfer/blob/d0fdf8346c840283bdbb4cc2f97c228204fa605a/FastSurferCNN/data_loader/data_utils.py#L206

with the error message
```
Volume: 0 Failed Reading Data. Error: index 470 is out of bounds for axis 0 with size 98
```

Concerning the first error, not sure the why values smaller than or equal to 251 are checked: the line
https://github.com/Deep-MI/FastSurfer/blob/d0fdf8346c840283bdbb4cc2f97c228204fa605a/FastSurferCNN/data_loader/data_utils.py#L516

masks the [251-255] range; following the error message, only the existence of CC labels needs to be asserted, thus in the [251-255] range, but the assertion is checking values smaller than 251. Of course, if I use (see below the call to the script)

```
--gt_name aseg.auto_noCCseg_reshape_fastsurfer.nii.gz \
```

and do not use `gt_nocc`, the above assertion works. If I understand correctly the script documentation, `--gt_name` is assumed to be FreeSurfer's `aparc.DKTatlas+aseg.mgz`, which contains ctx labels, thus, values in the 1000 and 2000 ranges.

Am I missing something?

Concerning the second error, the variable `class_wise_weights` is a 98 value vector, which corresponds to the number of different label values in `mapped_aseg`; `mapped_aseg` is a 256x256x256, volume, thus the indexing `class_wise_weights[mapped_aseg.ravel()]` does not work. Any suggestion of what I am missing?

The error persists if I use
```
--gt_name aseg.auto_noCCseg_reshape_fastsurfer.nii.gz \
```

and do not use `gt_nocc`, with slightly different index/size values
```
Volume: 0 Failed Reading Data. Error: index 42 is out of bounds for axis 0 with size 36
```

## Screenshots

Does not apply.

## Environment
 - FastSurfer Version: Code revision d0fdf8346c840283bdbb4cc2f97c228204fa605a (`stable` branch)
 - FreeSurfer Version: freesurfer-linux-ubuntu22_x86_64-7.3.2-20220804-6354275
 - OS: Ubuntu 22.04
 - CPU: Not relevant
 - GPU: Not relevant
 - Python: 3.8.16

In the provided link there is a text file with the output of `pip list`.

### Execution

Run Command:
```
python generate_hdf5.py \
--hdf5_name /path/to/mydataset.hdf5 \
--plane axial \
--csv_file /path/to/subj.csv \
--image_name t1w_reshape_fastsurfer.nii.gz \
--gt_name aparc.DKTatlas+aseg.mapped_reshape_fastsurfer.nii.gz \
--gt_nocc aseg.auto_noCCseg_reshape_fastsurfer.nii.gz \
--lut /path/to/freesurfer_color_lut_20150729.tsv \
--processing aseg \
--sizes 256
```
PS: `freesurfer_color_lut_20150729.tsv` has been renamed to `freesurfer_color_lut_20150729.tsv.txt` to enable uploading it to here.

[t1w_reshape_fastsurfer.nii.gz](https://github.com/Deep-MI/FastSurfer/files/11502997/t1w_reshape_fastsurfer.nii.gz)
[aseg.auto_noCCseg_reshape_fastsurfer.nii.gz](https://github.com/Deep-MI/FastSurfer/files/11503000/aseg.auto_noCCseg_reshape_fastsurfer.nii.gz)
[aparc.DKTatlas+aseg.mapped_reshape_fastsurfer.nii.gz](https://github.com/Deep-MI/FastSurfer/files/11503001/aparc.DKTatlas%2Baseg.mapped_reshape_fastsurfer.nii.gz)
[subj.csv](https://github.com/Deep-MI/FastSurfer/files/11503002/subj.csv)
[freesurfer_color_lut_20150729.tsv.txt](https://github.com/Deep-MI/FastSurfer/files/11503004/freesurfer_color_lut_20150729.tsv.txt)
[fastsurfer_env.txt](https://github.com/Deep-MI/FastSurfer/files/11503006/fastsurfer_env.txt)

**Comment by m-reuter** [comment]
Hi, concerning the first point. We remove all the CC labels, which are in that range, before training. The reason is that the left  and right boundaries of the CC are not really determined anatomically, it is defined to be 5mm thick. This is why CC is added at a later stage, currently in recon-surf, as it also requires to find the exact midplane. 
Maybe the second issue is a consequence of the first?

**Comment by jhlegarreta** [comment]
Thanks for answering @m-reuter.

>  We remove all the CC labels, The reason is that the left and right boundaries of the CC are not really determined anatomically, it is defined to be 5mm thick.

I am fine with the rationale. But as said in my comment, then the assert should check that the remaining labels have values other than [251-255], not smaller than.

> Maybe the second issue is a consequence of the first?

Unfortunately, it is not; as explained in my message, even if I use a label image that does not have the CC values or modify the assertion, the error still happens.

Please give a try to the data provided. The error should be easy to reproduce at the commit hash given.

**Comment by jhlegarreta** [comment]
BTW, happens with the head commit (8b559586f6245fbfd1bdab1d5d3de41e10d171d9) of the `dev` branch as well.

**Comment by m-reuter** [comment]
The assert that you mention happens only if you process an aseg with  processing == "aseg" (where no cortical parcellation labels should exist). For aparc you need to pass processing == "aparc"

**Comment by jhlegarreta** [comment]
> The assert that you mention happens only if you process an aseg with processing == "aseg" (where no cortical parcellation labels should exist). For aparc you need to pass processing == "aparc"

OK :+1: .

The second error error is independent of the above. In order to get the weights mask, the below code fixes the issue:
```
label2weight = dict({key: val for key, val in zip(unique, class_wise_weights)})

# Extract keys and values
k = np.array(list(mapping.keys()))
v = np.array(list(mapping.values()))

# Get argsort indices
sidx = k.argsort()

ks = k[sidx]
vs = v[sidx]
weights_mask = vs[np.searchsorted(ks, mapped_aseg)]
```

instead of
```
weights_mask = np.reshape(class_wise_weights[mapped_aseg.ravel()], (h, w, d))
```

I would say that the above fix computes the weights that you are trying to compute. The fix allows the HDF5 to be built.

You may be willing to fix this; or let me know if you want me to submit a PR.

**Comment by LeHenschel** [comment]
In short: you are getting the errors because you are i.) incorrectly using processing=aseg when processing an aparc and ii.) using an incorrect look-up table (way more classes than what the aparc actually has). 

To 1. assert not np.any(251 <= aseg)
as Martin mentioned this assertion happens if processing=aseg only because in this case there can not be any classes above 251. Corpus Callosum should be removed and the cortex labels are mapped to one common value (42 and 3). So the check is valid as is. 

To 2. weights_mask = np.reshape(class_wise_weights[mapped_aseg.ravel()], (h, w, d))
You are using an incorrect lut. Your Look-up table contains way more classes (around 1300) than what you have inside your segmentation volume. Hence, the mapping from aparc to the label space is wrong. You have lots of values around 400, and not one consecutive line from 0-max. In turn, you get an indexing error during create_weights. 
This error has nothing to do with the volume shape. As you mentioned, we calculate class_wise_weights based on the mapped_aseg. We later use the raveled version to index the weights (ravel linearizes the array, hence you get a sequence of the labels aka [0, 1, 2, 3, ...]). If you get an indexing error with 406, this means the class exists in the mapped_aseg even though it should not (we are already working with the mapped version of the aseg, hence the labels should be consecutive from 0-max, whereas for your image it jumps from 75 to 406 due to the incorrect LUT). 

When using the correct LUT and the correct processing, everything works perfectly fine. So there is no bug in the processing.
 
 Correct command:
`python $FASTSURFER_HOME/FastSurferCNN/generate_hdf5.py --hdf5_name ./mydataset.hdf5 --plane axial --csv_file ./subj.csv --image_name t1w_reshape_fastsurfer.nii.gz --gt_name aparc.DKTatlas+aseg.mapped_reshape_fastsurfer.nii.gz --gt_nocc aseg.auto_noCCseg_reshape_fastsurfer.nii.gz --lut $FASTSURFER_HOME/FastSurferCNN/config/FastSurfer_ColorLUT.tsv `

**Comment by jhlegarreta** [comment]
OK, thanks for the explanations. The
> Correct command:

solves the issue, and I am able to generate the HDF5 file.

The LUT I used was the FreeSurfer LUT, and the input data was computed using FreeSurfer. I had not foreseen the `0-max` related assumptions made when generating the HDF5 file, and I thought that the code would support using an arbitrary LUT, even if it contains additional labels that are not in the segmentation volume.

Thanks for the patience.

**Comment by LeHenschel** [comment]
Sure thing. Glad you got it working :). An arbitrary LUT is supported in general (just with the limitation that only the classes of interest should be in it), but I guess overall it would not hurt to explain the LUT a little more in the READMEs to avoid future confusion on this point.
