### ISSUE TITLE
Is it possible to conform an existing manual parcellation for comparison

### ISSUE THREAD

**Issue by HLorzel** [Deep-MI/FastSurfer#317]
I have a manual parcellation to go with the T1 Weighted file.  Is it possible to conform this in the same way that FastSurfer conforms the T1 such that I can compare the two?  Or alternatively, it is possible to have the labeled file produced in the same orientation as the original T1?

**Comment by m-reuter** [comment]
Either is possible. One issue is that mapping labels is not a good idea (due to the interpolation artifacts from the nearest neighbor interpolation, results after mapping will look pretty noisy along the boundaries). 
Since only image geometries are changed, not RAS coordiantes, you can simply run:
`mri_convert -rt nearest -rl <target_T1> <input_seg> <output_seg>`
or there is also a similar mri_vol2vol command with the flag --regheader .  Note, that these are FreeSurfer commands.

**Comment by HLorzel** [comment]
Just got this to work.  Thank you much.
