### ISSUE TITLE
Mask for tumors / prior surgeries

### ISSUE THREAD

**Issue by cristidonos** [Deep-MI/FastSurfer#32]
Hi. 
Amazing tool, thank you. 
We often see subjects with tumors or prior resections that results in distorted or even missing brain structures. Do you plan to implement mask usage to avoid segmentation errors on such abnormal brains? 
Thanks,
Cristi

**Comment by m-reuter** [comment]
Hi Cristi, we currently don't have the time to incorporate masks, but will keep this on the list for future updates. Tumors can also deform brains due to the mass effect and edema, or images often have enhancement agent, which will throw off the network even in healthy-looking areas, so it is unclear if a mask is sufficient. For resections, there is a higher chance that masks will work. Have you tested running these images and masking the results?
