### ISSUE TITLE
Longitudinal Processing

### ISSUE THREAD

**Issue by jrussell9000** [Deep-MI/FastSurfer#374]
I'd like to request adding a FreeSurfer-style longitudinal processing option (or documentation about how to do so manually). There's an ever-growing list of longitudinal consortium studies and it'd be phenomenal to start using FastSurfer to process those scans.

Not sure how big of an ask this is.  In the interim, it _seems_ as though one could simply script the standard FreeSurfer longitudinal pipeline to run with FastSurfer (with no need to change the MLing).  I'm more than willing to try this or if DEEP-MI has any code/docs about how to do so, that would be fantastic as well.

**Comment by m-reuter** [comment]
Hi @jrussell9000 this is on our list since a long time. We recently received some funding for this so a longitudinal pipeline for the surfaces should hopefully be developed soon. Since the processing steps are different between recon-all and FastSurfer it is not quite as straight forward as you may think. Additionally we were working on a planned switch to snakemake pipeline building toolkit before doing the longitudinal stream, in order to not have to do it twice. But due to urgent demand, we may not stick with that order. 

One thing to note is, that based on our tests FastSurfer already outperforms FreeSurfer (cross sectional) with respect to subcortical volumes on longitudinal data and is en par with the FreeSurfer longitudinal stream there. Only the surface stream is not quite as good as FreeSurfer-long and somewhere between that and the independent FreeSurfer processing.

**Comment by jrussell9000** [comment]
Thanks for such a rapid response @m-reuter ! I suspected it might not be that simple. My group is game planning a grant-funded project reprocessing a very large number of longitudinal scans and were _hoping_ we could use FastSurfer in part or in whole. I'll eagerly await new developments!

**Comment by m-reuter** [comment]
We can keep it open, until it is ready :-)

**Comment by m-reuter** [comment]
Hi #588 now adds support for longitudinal processing (still experimental, not tested much, and not tested at all on sub-mm images, which may require a little more work). 
Will close this for now. Feel free to open a new issue if you find any issues with the longitudinal stream.
