### ISSUE TITLE
How to perform regional analysis on non-T1 modality?

### ISSUE THREAD

**Issue by karllandheer** [Deep-MI/FastSurfer#385]
Hello, I have run FastSurfer (great package), to get brain parcellations in what I'm calling the FastSurfer T1 space (because it re-samples the image to 256x256x256 isotropic). What is the recommended way to perform regional analysis on non-T1 modalities (say T2)? A simple thing I tried was to simply register the T2 to the FastSurfer T1, however this will be dependent on the quality of such registration, which is never perfect. Given that the transformation to go from T1 original to FastSurfer T1 is exactly known, it's a bit like poorly re-inventing the wheel. Is there another recommended way? Such as an output transformation or the like? Any help would be greatly appreciated!

**Comment by m-reuter** [comment]
Hi, yes, FastSurfer uses its own space (similar to FreeSurfer) with isotropic voxels. But different from FreeSurfer, we resample to the shortest voxel size, so it could also be .8mm isotropic or anything else. 

About your T2 question. In order to do regional analysis in the T2 image, you need a registration between the T2 and the T1 anyway, so you might as well register with the FastSurfer isotropic T1 rather than the original. Either way it depends on how good that registration is. mri_coreg in FreeSurfer is probably a good tool to get that done, or also bb_register (which should work well when registering fMRI, diffusion etc). 

And you are right, the transformation from the original T1 and the isotropic FastSurfer T1 space is know. It is stored in the image headers, as the world coordinates remain the same and the voxel to world (RAS) coordinates are adjusted accordingly. That is also why viewers like Freeview show you the two images on top of each other. So if you already have a registration from somewhere to the original T1 image you can just ask the resampling tool to map it and then additionally reslice it like the isotropic fastsurfer T1, e.g. :

```mri_conver -at <transform from T1 to original T1.lta> -rl <isotropic T1.mgz> -rt cubic T2.mgz T2_in_fastsurfer_space.mgz```

This will apply the transform (-at) then reslice like the other T1 (-rl) use cubic interpolation (resample type -rt) the input to the output.
