### ISSUE TITLE
Help wanted

### ISSUE THREAD

**Issue by sandeepganji** [Deep-MI/FastSurfer#41]
Can you guys give me an example workflow for using your docker fastsurfer:CPU on a Windows 10 host?
Thank you,
-SG

**Comment by LeHenschel** [comment]
Hey SG,

unfortunately, we do not use windows here :(. Are you encountering any specific problem with running the image? If I am not mistaken, Windows and MAC both use Docker Desktop. For running FastSurfer on MAC, you need to adjust the memory settings because these are set to 2GB by default and FastSurfer needs around 10GB (see also #40 ). According to the Documentation, in Windows it is the same so if you see a similar error you can try to adjust the memory resources accordingly (see: https://docs.docker.com/docker-for-windows/ on how to do it, pretty much the same as for MAC).

Otherwise it would be helpful if you could state where exactly you get stuck.

Hope this helps. 

Best,
Leonie
