### ISSUE TITLE
 "--gt_nocc" when using generate_hdf5.py

### ISSUE THREAD

**Issue by gmeng92** [Deep-MI/FastSurfer#410]
I am currently trying to modify the FastSurferCNN so I can train using my own data (seg was labeled using WM,GM, CSF etc.). Since I don't have the  aseg_nocc like file as in FreeSurfer output, is it reasonable to set the gt_noncc as None?

**Comment by dkuegler** [comment]
The prepare_dataset script is customized to read freesurfer aseg/aparc-like output.

You probably need to adapt that part of the script as this is a very specific thing for aseg+aparc segmentations. I would probably just go into the code modify the parts that map the labels. So it is probably a couple more changes that you will need to do in the code.

**Comment by gmeng92** [comment]
Great, Thanks! Good to know that. BTW, any particular reason to add the non corpus callosum segmentation when using the aseg+aparc segmentations as ground truth?

**Comment by m-reuter** [comment]
Hi, corpus callosum does not really have a border left and right. In freesurfer it is segmented in 5 slices after reorienting the brain and finding the mid-slice (plus the two on each side). That gives it a predefined width of 5mm. After segmentation in this space, labels get mapped back into the original image space (not great, as that introduces interpolation artefacts from nearest neighbour interpolation). For deep learning it would be difficult to know where to stop segmenting in the left right direction which is why we add the CC later.
