### ISSUE TITLE
lh/rh.aparc.pial.stats

### ISSUE THREAD

**Issue by karllandheer** [Deep-MI/FastSurfer#455]
Hello, these pial stats files are generated by freesurfer, but I do not see them being generated by my FastSurfer run. Are they not included, or am I not running something correctly?

**Comment by m-reuter** [comment]
This is part of Freesurfer's  recon-all parcstats block:
https://github.com/freesurfer/freesurfer/blob/6d31c4b244455f8f35414fc719e8d51a6e166416/scripts/recon-all#L5006

We call that block from recon-surf here:
https://github.com/Deep-MI/FastSurfer/blob/8c20ccac821e07fb73153f6f3698f9a719674a82/recon_surf/recon-surf.sh#L972

so it should be created.

**Comment by karllandheer** [comment]
I see, any ideas on why this would not be created? Actually, lh.aparc.stats is also not generated... 

this is the command I am using to run FastSurfer:

docker run -v ${SETUP_DIR}:/data my_fastsurfer:cpu --t1 /data/T1_unbiased_brain.nii.gz --sd /data/ --sid Tutorial --py python3 --allow_root --${field} --fs_license /data/FreeSurferLicense.txt --parallel --threads 2')

**Comment by m-reuter** [comment]
This block only gets run if you pass the `--fsaparc` flag. The reason is that we use the DKT Atlas by default and if you want results from the older FreeSurfer DK atlas you need to get it the FreeSurfer way (via spherical registration to their atlas). This is switched on by the flag.

**Comment by karllandheer** [comment]
ah ok, great. I see it says this is slower. Do you have a rough estimate for how much slower this is? (i.e., does it take 20% longer, 50% longer, etc?). Compute costs are a concern is why I ask

**Comment by m-reuter** [comment]
The spherical registration is a little slow, but if you plan to do a group analysis later, you need it anyway (which is why we switch it on by default in recent FastSurfer versions and can be manually switched off via `--no_surfreg`). So given that that part runs anyway, the overhead for the `--fsaparc` should not be too long, but you need to check. 

Note, however, that this flag will use FreeSurfer's atlases for all surface segmentations, also for the DKT, so results in the  surface stats files will come from Freesurfer and not any longer from our projected deep-learning segmentation. Ours can still be found in `$hemi.aparc.DKTatlas.mapped.stats` but are not painted any longer into the aparc+aseg.mgz.

**Comment by m-reuter** [comment]
Closing this for now. If you like, you can document here how much more time the --fsaparc finally took on your system.
