### ISSUE TITLE
error with subject list in FastSurfer on multiple subjects

### ISSUE THREAD

**Issue by winebeer1** [Deep-MI/FastSurfer#502]
## Question/Support Request

Hello, I'm trying to do FastSurfer on multiple subjects. 
But I have some errors and I have no idea how to fix although I've spent the entire day trying to resolve errors.

**The command I used:**
```
docker run
-v /ddd/t1/FastSurfer_DATA2:/data 
-v /ddd/t1FastSurfer:/output
-v /ddd/t1/fs732:/fs_license
--entrypoint "/fastsurfer/brun_fastsurfer.sh"
--rm --user $(id -u):$(id -g) deepmi/fastsurfer:latest
--fs_license /fs_license/license.txt
--device cpu 
--sd /output 
--subject_list /data/subjects_list.txt
--parallel --3T --seg_only
```

**Output messages:**
```
/fastsurfer/brun_fastsurfer.sh --fs_license /fs_license/license.txt --device cpu --sd /output --subject_list /data/subjects_list.txt --parallel --3T --seg_only
Fri, 05 Apr 2024 08:33:49 +0000

INFO: run_fastsurfer not explicitly specified, using $FASTSURFER_HOME/run_fastsurfer.sh.
) could not be found. Must supply an existing T1 input (full head) via 
--t1 (absolute path and name) for generating the segmentation.
NOTES: If running in a container, make sure symlinks are valid!
```

I tried to create various versions of subjects_list.txt files, but it didn't work with the same result

(1) subjects_list1.txt
```
220823=/data/220823/220823.nii.gz
231026=/data/231026/231026.nii.gz
211206=/data/211206/211206.nii.gz
231003=/data/231003/231003.nii.gz
```

(2) subjects_list2.txt
```
220823=/data/220823
231026=/data/231026
211206=/data/211206
231003=/data/231003
```

(3) subjects_list3.txt (also tried using absolute paths, but it didn't work too)
```
 220823=/ddd/t1/FastSurfer_DATA2/220823
```

I also checked if there was a space between the subjects, but there was none. 
Is there other issues (not subject list) I am missing?

I'm fairly new to Ubuntu and Docker, so I would really appreciate your help.

Thank you in advance.

## Environment
 - FastSurfer Version: I'm using docker and I have no idea how to figure out my FastSurfer version
 - Installation type: official docker
 - OS: Linux (Ubuntu)
 - GPU: none

**Comment by dkuegler** [comment]
Hi,

version: multiple options: run "run_fastsurfer.sh --version" or in "/subjects_dir/subject/scripts/build.log". The point being, that there are also different version of the official docker... `deepmi/fastsurfer:latest` is just a pointer to the most recent version (but it does not auto-update)
you can run brun_fastsurfer with the additional `--debug` option, that gives more information to help find what is going on.
I am not really sure, what error you are reporting, it seems to me you are not sharing the error message?

I think your issue is that you edit your subject_list files on Windows, which puts line endings as carriage return + newline. This breaks things in some settings. We had a similar issue in #438 and #454. I'd also recommand looking into the `--threads` flag with `--device cpu` (see those issues).

Kind regards,
David

**Comment by winebeer1** [comment]
Hello, 
Thank you for your quick response.

Actually, I was working with the subject list file on MacOS and then dragged and dropped it into the Ubuntu environment. After reading your answer, I tried to create the subject list file directly in Ubuntu using the terminal, and it finally worked well!
I can't thank you enough!

Thank you so much!

**Comment by dkuegler** [comment]
I think the MacOS Line endings used to be carriage return only, so if you have an old MacOS Version that might be the reason. 
I am going to close this issue now, as it seems fixed.
