### ISSUE TITLE
Website hosting checkpoints down

### ISSUE THREAD

**Issue by GuillaumeTh** [Deep-MI/FastSurfer#536]
I'm trying to download checkpoints using download_checkpoints.py in FastSurfer v2.2.0 however the website https://b2share.fz-juelich.de/api/files/a423a576-220d-47b0-9e0c-b5b32d45fc59 looks down.

Could you check to resolve the issue?

Best

**Comment by dkuegler** [comment]
Hi,

we are aware of the issue. As explained [here](https://github.com/Deep-MI/FastSurfer/issues/518#issuecomment-2191703119), this is already fixed in dev. For now, you can also download the checkpoints from zenodo (find the path in `**/config/checkpoints_path.yaml` of the `dev` branch for each module. Or just download the weights with "dev" and use with "stable".

The docker images also come with the weigths downloaded.

Cheers

**Comment by xuansean** [comment]
> Hi,
> 
> we are aware of the issue. As explained [here](https://github.com/Deep-MI/FastSurfer/issues/518#issuecomment-2191703119), this is already fixed in dev. For now, you can also download the checkpoints from zenodo (find the path in `**/config/checkpoints_path.yaml` of the `dev` branch for each module. Or just download the weights with "dev" and use with "stable".
> 
> The docker images also come with the weigths downloaded.
> 
> Cheers

Hi,

Just letting you know that I tried the zenedo url in the dev and it seems like the zenedo url is currently down as well(saying page not found):
(fastsurfer) ➜  FastSurfer git:(dev) cat ./FastSurferCNN/config/checkpoint_paths.yaml

url:
- "https://b2share.fz-juelich.de/api/files/a423a576-220d-47b0-9e0c-b5b32d45fc59"
- "https://zenodo.org/records/10390573/files"


Best,

**Comment by dkuegler** [comment]
Sorry, the link is https://zenodo.org/records/10390573 .

The download with the script from dev should also work (it did work yesterday).

**Comment by dkuegler** [comment]
The b2share server from Jülich is up again, so all downloads should work without modifications again.

**Comment by GuillaumeTh** [comment]
Thank you very much !
