### ISSUE TITLE
Reference to deprecated docker images in surface pipeline docs

### ISSUE THREAD

**Issue by sRassmann** [Deep-MI/FastSurfer#544]
In docs for the surface pipeline (`recon_surf/README.md`) the docker image for performing only the surface reconstruction from an existing segmentation using singularity (Examples 1 & 2) does not exist (anymore) ("docker pull deepmi/fastsurfer:surfonly-cpu-v2.0" and "singularity build fastsurfer-reconsurf.sif docker://deepmi/fastsurfer:surfonly-cpu-v2.0.0")
Probably the right image is "deepmi/fastsurfer:cpu-v2.2.0" as referenced in commands below.

Edit:
Also, both example commands seem to lack the `--seg_only` flag to skip the segmentation as assumed in the description.

**Comment by m-reuter** [comment]
yes, thanks. For the version I think we need to decide if we put "latest" everywhere, but then we run into the problem that users think they have the latest locally while it has changed on docker hub. So probably better we put 
```-v*.*.*``` into the documentation and add some text how the user can find out the latest release version themselves on docker hub. 

Furthermore, we stopped providing a surf only docker container. In that old container one did not need the ```--surf-only``` flag (```--seg-only``` would not work at all), because the entry script is different and would only run the surface pipeline for a given image and segmentation pair, this allowed the user to specify a few more parameters than when using the run_fastsurfer entry point. But in order to reduce the number of docker images and the number of supported ways to interact with fastsurfer we dropped this. 

The readme needs to be updated before the next release.

**Comment by m-reuter** [comment]
I fixed the main problems with version strings and outdated images. In the future we can add an example to change the entry point in docker and directly run recon-surf.

**Comment by sRassmann** [comment]
There still seems to be an inconsistency in the docs as directly calling the `recon-surf.sh` does not accept the `--surf_only` flag:

```
singularity exec [...] fastsurfer-cpu.sif /fastsurfer/recon_surf/recon-surf.sh [...] --surf_only
ERROR: Flag --surf_only unrecognized.
```
while it requires a T1 per default, i.e. running the script on an FastSurfer output dir without the T1 (and not setting the flag) results in:

```
singularity exec [...] fastsurfer-cpu.sif /fastsurfer/recon_surf/recon-surf.sh [...]  # --surf_only
ERROR: T1 image () could not be found. Must supply an existing T1 input (conformed, full head) via --t1 (absolute path and name).
```

The expected behaviour can be achieved using
```
singularity exec [...] fastsurfer-cpu.sif /fastsurfer/run_fastsurfer.sh [...]  --surf_only
```
similar to the docker example.

**Comment by dkuegler** [comment]
I just went through the git history and I am pretty sure this behavior has been expected since Fastsurfer 1.0.0.

So this is an error in the documentation.

**Comment by m-reuter** [comment]
I updated the readme accordingly. Let me know if you find more inconsistencies. Thanks.
