### ISSUE TITLE
Please share the image id of the ADNI/OASIS datasets for training the model

### ISSUE THREAD

**Issue by yunghx** [Deep-MI/FastSurfer#589]
Hi,

Thank you for the nice release of the model, it indeed can accelerate the parcellation of the brain in MRI. We are now trying to apply the algorithm to ADNI and OASIS datasets. But noticed that the model was trained on some images from these datasets. 

Can you please provide me the image ids of the training images? So that we can avoid these examples when doing the down-selection from our side, and therefore avoid any mess of training/testing image issues.

Best,
HX

**Comment by dkuegler** [comment]
Hello,

This is the training dataset list for v2.0.X 
[aparc_training_dataset_v2.0.0-no_rhineland.txt](https://github.com/user-attachments/files/17306847/aparc_training_dataset_v2.0.0-no_rhineland.txt)
[aparc_validation_dataset_v2.0.0-no_rhineland.txt](https://github.com/user-attachments/files/17329171/aparc_validation_dataset_v2.0.0-no_rhineland.txt)

I have removed the images from the rhineland study, because the indices are not "unique", because of anonymization. Your rhineland dataset will have completely different case to id assignments.

Cheers

**Comment by m-reuter** [comment]
Also note, if you are trying to apply FastSurfer to ADNI or OASIS that is fine, if you are analysing that data. You don't need to know what cases were training cases. 

If your goal is to compare different methods, then you need to retrain all methods on the same data to have a fair comparison (also you may even need to adjust other parameters of the models). We make available our training scripts.

**Comment by yunghx** [comment]
Many thanks for the replies! We are actually working for AD-based feature extraction, maybe the current tool is valid for us already.

**Comment by dkuegler** [comment]
The general rule should be: 
You should not use data that was previously used for training in later stages for testing (results that inform quality).
Given this information, using those training cases as part of your training cases for this downstream application is fine. Using them as testing cases (to report on quality) should be avoided as to not overfit on this data.
I would expect the negative effect of this "overfitting" to be **very** limited, but if you want to be extra careful, this is what I would advise.

I have also added the validation dataset in the answer above (as it would also be methodologically "better" in this case to exclude these cases from the testing data -- they could be used to train or find parameters, but not for calculating final performance).
