### ISSUE TITLE
Issue with FastSurfer checkpoint download and execution

### ISSUE THREAD

**Issue by chenxiaoya-xiaoyi** [Deep-MI/FastSurfer#622]
Dear FastSurfer Developers,

## Question/Support Request
I am encountering issues with downloading the FastSurfer checkpoint files and executing the pipeline. Despite following the documentation for a native installation, the following problems occur:

Checkpoint Download Issue:

When trying to download the aparc_vinn_sagittal_v2.0.0.pkl file from the provided link:
https://b2share.fz-juelich.de/api/files/a423a576-220d-47b0-9e0c-b5b32d45fc59/aparc_vinn_sagittal_v2.0.0.pkl,
the file downloads successfully but is only 20 MB, which does not match the expected size, and the MD5 checksum does not match.
I also tried downloading the file from Zenodo using:
wget -O aparc_vinn_sagittal_v2.0.0.pkl "https://zenodo.org/record/10390573/files/aparc_vinn_sagittal_v2.0.0.pkl"
but the connection fails with the error:
Connection refused.

Execution Issue:
After manually downloading some of the checkpoint files and running the pipeline using:

bash /home/hello/1_applications/FastSurfer/run_fastsurfer.sh --fs_license /opt/freesurfer/license.txt --t1 /home/hello/9_data/test/ms002_20191117_T1.nii.gz --sd /home/hello/9_data/test --sid ms002_20191117_T1 --device cuda  

I encounter the following error:
WARNING: FastSurferCNN.utils.checkpoint:Server https://zenodo.org/records/10390573/files not reachable (ConnectionError): HTTPSConnectionPool(host='zenodo.org', port=443): Max retries exceeded with url: /records/10390573/files/aparc_vinn_sagittal_v2.0.0.pkl (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fff89766fa0>: Failed to establish a new connection: [Errno 111] Connection refused'))
ERROR: FastSurfer asegdkt segmentation failed.

It appears that the pipeline is unable to access the checkpoint files, even when some of them are downloaded manually.

## Screenshots / Log files
Below is a screenshot of the error log from the execution:

![image](https://github.com/user-attachments/assets/542a69c2-1e7f-4da0-a2fa-0bed235ca964)

## Environment
FastSurfer Version: [Run run_fastsurfer.sh --version all and attach output]
Installation type: native (step1:git clone --branch stable https://github.com/Deep-MI/FastSurfer.git; step2: python3 /FastSurfer/FastSurferCNN/download_checkpoints.py (but this step did not work)).

FreeSurfer Version: 6.0
OS: Ubuntu 22.04
GPU: NVIDIA RTX 4000

### Execution Command
bash /home/hello/1_applications/FastSurfer/run_fastsurfer.sh --fs_license /opt/freesurfer/license.txt --t1 /home/hello/9_data/test/ms002_20191117_T1.nii.gz --sd /home/hello/9_data/test --sid ms002_20191117_T1 --device cuda  

Additional Notes:
I suspect the checkpoint download issue might be due to server or regional restrictions. If possible, could you provide alternative download methods (e.g., Google Drive links, alternative mirrors)?

I have also tried setting up Docker as per the documentation, but I encounter network connection errors when pulling the Docker images (Client.Timeout exceeded while awaiting headers).
Please let me know if more information is required to resolve these issues. Thank you for your assistance!

Best regards,
Xiaoya Chen

**Comment by m-reuter** [comment]
Hi, it can be that these online services (Zenodo and Jülich) are sometimes down or have issues, waiting solves this. 

It could also be that the manually downloaded files are not the right ones, but older versions, or they were placed in the wrong paths. Also Cerebnet and other networks need weights, not only FastSurferVINN. 

Finally I notice that your FreeSurfer version 6.0 is not supported to work with FastSurfer, you would need to upgrade that to 7.4.*.  (only relevant if you plan to run the surface module).

We have a python script that downloads checkpoints, maybe delete the manually downloaded ones and try to run the script for download in FastSurferCNN/download_checkpoints.py . FastSurfer runs this automatically the first time it is started to download the weights, so you can just start it. If that fails it is usually a problem with file servers and should be fixed by them quickly. Later today we will try to replicate. 

Alternative: use docker or singularity. 

Also: please always post the FastSurfer version you are using? Is it the latest release in stable, or the dev branch? (dev can always have issues as it is not tested).

**Comment by m-reuter** [comment]
I tried to replicate, the download_checkpoints.py is working for me (from Zenodo). Your file names above are the correct versions and also the file size per pkl file is 21MB, which is correct. 

Also if you place the downloaded files into the checkpoints directory, it should see them and not try to download them again, so something did not work with your manual download.

**Comment by chenxiaoya-xiaoyi** [comment]
Thank you so much for your previous suggestions! The issue was resolved after upgrading to FreeSurfer version 7.4.1 and obtaining the complete checkpoint files. The process completed successfully.

However, I still encountered some warnings/errors during the execution. I would greatly appreciate your assistance in addressing them.

Thank you once again for your continued support!
![image](https://github.com/user-attachments/assets/a8ad3779-c8e4-47eb-9b3d-8cd7b2dac950)

**Comment by m-reuter** [comment]
I still don't know what FastSurfer version you are using. You can run ```run_fastsurfer.sh --version all``` to find out.

Anyway, these are just warnings that our script to extract run times did not find some strings in the log file. We may need to adjust that, but it is nothing to worry about. Looks like otherwise everything should have been processed successfully.

**Comment by chenxiaoya-xiaoyi** [comment]
Thank you for your response!

The FastSurfer version I am using is 2.4.0-dev+bd3f8f5 (dev).

I appreciate the clarification regarding the warnings and am glad to hear they are not critical.

Thank you again for your help and support!

**Comment by dkuegler** [comment]
Hi @chenxiaoya-xiaoyi,

please do not use the dev-version for "production" (research output). Please use stable (or 2.3.3).

dev may have bugs and produce bad results and is **always** experimental!

Cheers
