### ISSUE TITLE
Running with FreeSurfer v7

### ISSUE THREAD

**Issue by LucasCampos** [Deep-MI/FastSurfer#66]
Hello,

I see in the [`recon_surf.sh` pipeline](https://github.com/Deep-MI/FastSurfer/blob/8fafb9b82e4aa966e7de89eed2d169bd60e5bdfc/recon_surf/recon-surf.sh#L279) that using FastSurfer with FreeSurfer v7 is not recommended. Is this still the case? If so, is the issue that FastSurfer was trained exclusively on FreeSurfer 6.0 data (as per issue #47) or is there something else?

What could be done to run FastSurfer with FreeSurfer v7?

Bests,
Lucas

**Comment by m-reuter** [comment]
Hi, yes, we noticed some reduced test-retest reliability values in FreeSurfer V7. Not sure this is still true for 7.2 (we haven't tested). This was tested and shown directly in vanilla FreeSurfer. FastSurfer inherits those problems if we switch to using the FreeSurfer 7.1 binaries for surface processing. 
Not sure why you want to use FreeSurfer 7? If you want to test things you can either:
- try what happens if you source FS7 instead of 6 and run the pipeline (could fail). This scenario would use FS7 binaries, but the pipeline (recon-surf) would be more similar to how things are done in FS6.
- I started to adopt recon-surf to the 7.1 recon-all steps a while ago and can share that script for testing. 

Anyway, short answer, FS 71 is not recommended, and 7.2 is not tested.

**Comment by BarryLiu97** [comment]
Hi, I'm new here and I have a similar question. And may I ask what's the difference between 6 and 7? From what I saw, 7 is a lot faster than 6.

**Comment by m-reuter** [comment]
For differences between FreeSurfer versions consult their webpages, e.g. 
https://surfer.nmr.mgh.harvard.edu/fswiki/ReleaseNotes 
and mailing list. We are currently exploring basing our surface pipeline on FS72 especially for high-res processing.

**Comment by m-reuter** [comment]
With #114 this has been added to the dev branch and is currently undergoing testing.

**Comment by m-reuter** [comment]
Finally we found the cause for the reduced test retest reliability. We now replace FreeSurfer's global alignment on the sphere with our own code (see #164 ). This has been tested in the dev branch. It was the last thing holding us back to upgrade our FreeSurfer dependency to 7.2 and release a new version of FastSurfer.
