### ISSUE TITLE
Surface models on Google Colab

### ISSUE THREAD

**Issue by Sebagam** [Deep-MI/FastSurfer#96]
Hi all, 

I'm trying to run the third part of the uploaded notebook directly on Google Colab (Use case 3 - Surface models, Thickness maps and more: FastSurfer's recon-surf command). 

After installing FreeSurfer and running this line, for example:

!./run_fastsurfer.sh --t1 /content/AR_F17_DF_202.nii --sid 1

I get this error:

  File "eval.py", line 18, in <module>
    import nibabel as nib
ModuleNotFoundError: No module named 'nibabel'

By the way, it would be nice if you could upload a step-by-step fully working surface analysis on Colab.

Thanks,
Sebastian

**Comment by LeHenschel** [comment]
Hey Sebastian,

if you are running it in the Google Colab, you can just add a cell executing the installation (pip install nibabel). As far as I know it is not possible to install FreeSurfer in the Colab due to space limitations which is why we can not have a fully step-by-step surface analysis there. If you managed to do it, it would be very helpful to know how so we can integrate it.

Thanks,
Leonie
